---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rabe-backsage
  title: RaBe Backstage
  description: Our overengineered developer portal
  annotations:
    github.com/project-slug: radiorabe/rabe-backstage
    backstage.io/techdocs-ref: dir:.
spec:
  owner: it-reaktion
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rabe-backstage
  title: RaBe Backstage
  description: |
    All-in-one Backstage app for RaBe.
  annotations:
     github.com/project-slug: radiorabe/rabe-backstage
     backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: it-reaktion
  lifecycle: experimental
  system: rabe-backstage
  dependsOn:
    - component:default/rabe-ubi9-minimal
