name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.22.0
    with:
      image: 'ghcr.io/radiorabe/backstage'
      name: 'backstage'
      display-name: 'RaBe Backstage'
      tags: 'minimal rhel9 rabe backstage'
      cosign-base-image-only: true
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.22.0
