name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
    with:
      image: 'ghcr.io/radiorabe/backstage'
      name: 'backstage'
      display-name: 'RaBe Backstage'
      tags: 'minimal rhel9 rabe backstage'
      cosign-base-image-only: true
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
