name: Test

on:
  pull_request:

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
  test-yarn:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: write
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    strategy:
      matrix:
        node-version: [24]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn lint --format=json --output-file=eslint_report.json --since=37baf355806bdfdf5d6db7ec3e1d223640638206
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@5a8d8ab89a57679e90c32750e0f382e9d8570750 # v4
      with:
        report-json: "eslint_report.json"
        only-pr-files: false
      continue-on-error: true
    - run: yarn tsc
    - run: yarn test
  test-playwright:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: write
      contents: read
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
      - run: yarn install --immutable
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-test-report/
          retention-days: 30
